### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jjasghar**
Added the build badge per the new Chef Partner cookbook guide guidelines.

### CODE REVIEW

**Comment by metmajer** [comment]
@jjasghar can you please check the failure logs? Seems like builds are breaking on your end.

**Comment by jjasghar** [comment]
Yep, got em fixed.

Can you take care of: https://jenkins-01.eastus.cloudapp.azure.com/job/dynatrace-cookbook/93/console for me? Thanks! 🤘

**Comment by metmajer** [comment]
@jjasghar some of the error message are a little picky. We'll see what we can do. How can we replicate the output locally? We should make this part of our upstream process then. Cheers!

**Comment by jjasghar** [comment]
Yep, we have all our jobs posted here: https://github.com/chef-partners/chef-partner-cookbook-program-jjb your specifically: https://github.com/chef-partners/chef-partner-cookbook-program-jjb/blob/master/jobs/dynatrace-cookbook.yml

PR's are more then welcome, and we'd like to have a more visible continual validation/certification :)

**Comment by metmajer** [comment]
I'll have a closer look into this soon! Will `chef-exec-rspec-spec` execute our kitchen tests? By the way, a fix from our dev team is already underway.

**Comment by pozieblo** [comment]
I fixed issues reported by `chef-exec-rubocop` on master branch. The remaining validation tasks (`chef-exec-foodcritic` and `chef-exec-rspec-spec`) also pass with status 0 (OK). It seems that the  `chef-exec-rspec-spec` is a noop for now.

**Comment by jjasghar** [comment]
@pozieblo looks like you missed one thing :(

```
[dynatrace-cookbook] $ /bin/bash /tmp/hudson7364832001878912519.sh
Inspecting 84 files
...............C....................................................................

Offenses:

attributes/server_update.rb:1:1: C: Carriage return character detected.
# ...
^

84 files inspected, 1 offense detected
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by jjasghar** [comment]
https://github.com/Dynatrace/Dynatrace-Chef/pull/22

**Comment by pozieblo** [comment]
I fixed the issue on master. For some reason CRLF characters were injected into the attributes/server_update.rb file (instead of LF) maybe because I have started playing with the autocrlf git config attribute...

**Comment by jjasghar** [comment]
Wonderful! It's green now, thank you so much for the help :)

**Pull request merged**
